apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: shopnow
data:
  SPRING_DATASOURCE_URL: "postgresql://postgres:postgrespassword@postgres:5432/shopnow_notification"
  KAFKA_BROKERS: "kafka:29092"

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: shopnow
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXNzcGFzc3dvcmQ=

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: shopnow
spec:
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
  selector:
    app: notification-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: shopnow
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: notification-service
          image: shopnow/notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: SPRING_DATASOURCE_URL
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: notification-service-config
                  key: KAFKA_BROKERS
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: shopnow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-service-netpol
  namespace: shopnow
spec:
  podSelector:
    matchLabels:
      app: notification-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
