apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: shopnow
data:
  SPRING_DATASOURCE_URL: "postgresql://postgres:postgrespassword@postgres:5432/shopnow_payment"
  KAFKA_BROKERS: "kafka:29092"

---
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: shopnow
type: Opaque
data:
  # Base64 values for: sk_test_mockStripeSecretKey2026
  STRIPE_SECRET_KEY: c2tfdGVzdF9tb2NrU3RyaXBlU2VjcmV0S2V5MjAyNg==

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: shopnow
spec:
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
  selector:
    app: payment-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopnow
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: payment-service
          image: shopnow/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
          envFrom:
            - configMapRef:
                name: payment-service-config
          env:
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: payment-service-secrets
                  key: STRIPE_SECRET_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-service-hpa
  namespace: shopnow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: payment-service-netpol
  namespace: shopnow
spec:
  podSelector:
    matchLabels:
      app: payment-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
