apiVersion: v1
kind: ConfigMap
metadata:
  name: search-service-config
  namespace: shopnow
data:
  ELASTICSEARCH_URL: "http://elasticsearch:9200"
  REDIS_URL: "redis://redis:6379"
  KAFKA_BROKERS: "kafka:29092"

---
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: shopnow
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: search-service
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: shopnow
  labels:
    app: search-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: search-service
          image: shopnow/search-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: search-service-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8088
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: search-service-hpa
  namespace: shopnow
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-service
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search-service-netpol
  namespace: shopnow
spec:
  podSelector:
    matchLabels:
      app: search-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector: {}
  egress:
    - to:
        - namespaceSelector: {}
